spring.application.name=estacionamento-api

spring.mvc.locale-resolver=fixed
spring.mvc.locale=pt_BR

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./data/estacionamento
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=com.joaovitor.estacionamento_api.web.controller

